import { Printer, Plus, Globe, MessageCircle, FileText } from 'lucide-react';
import { Modal } from './ui';
import { usePOS } from '../lib/store';
import { fmtRs, fmtDateTime, PAYMENT_LABEL, salePayments, POINT_VALUE, waLink } from '../lib/utils';
import type { Sale } from '../lib/types';
import InvoiceSheet from './InvoiceSheet';

export function ReceiptSheet({ sale, forPrint }: { sale: Sale; forPrint?: boolean }) {
  const { state } = usePOS(); const st = state.settings;
  return <div className={forPrint ? 'print-area' : 'w-full'} style={{ fontFamily: 'JetBrains Mono, ui-monospace, monospace' }}><div className={`${forPrint ? 'w-[72mm]' : 'w-full'} bg-white text-black p-5 text-[12px] leading-relaxed`}>
    <div className="text-center"><div className="flex justify-center mb-1.5"><span className="w-8 h-8 rounded-lg bg-black text-white flex items-center justify-center"><Globe size={15} /></span></div><div className="font-bold text-[15px] tracking-wide">{st.shopName.toUpperCase()}</div><div className="text-[10px]">{st.address}</div><div className="text-[10px]">{st.phone} · {st.email}</div></div>
    <div className="border-t border-dashed border-black my-3" /><div className="flex justify-between text-[11px]"><span>Bill: <b>{sale.billNo}</b></span></div><div className="flex justify-between text-[11px]"><span>{fmtDateTime(sale.date)}</span><span>Cashier: {sale.cashierName.split(' ')[0]}</span></div><div className="text-[11px]">Customer: {sale.customerName}</div>
    {sale.note && <><div className="border-t border-dashed border-black my-3" /><div className="text-[10px]"><span className="font-bold">Note:</span> {sale.note}</div></>}
    <div className="border-t border-dashed border-black my-3" /><table className="w-full text-[11px]"><thead><tr className="text-left"><th className="font-bold pb-1">Item</th><th className="font-bold pb-1 text-center">Qty</th><th className="font-bold pb-1 text-right">Amount</th></tr></thead><tbody>{sale.items.map((it,i)=><tr key={i}><td className="pr-2 py-0.5 align-top">{it.name}<div className="text-[9px] opacity-70">@ {fmtRs(it.price)}{it.discount ? ` · line disc -${fmtRs(it.discount,false)}` : ''}</div>{it.imeis?.length ? <div className="text-[9px] opacity-80">IMEI: {it.imeis.join(', ')}</div> : null}{it.serials?.length ? <div className="text-[9px] opacity-80">S/N: {it.serials.join(', ')}</div> : null}{it.warrantyMonths ? <div className="text-[9px] opacity-80">Warranty: {it.warrantyMonths} mo</div> : null}</td><td className="text-center align-top py-0.5">{it.qty}</td><td className="text-right align-top py-0.5">{(it.price*it.qty-(it.discount||0)).toLocaleString()}</td></tr>)}</tbody></table>
    <div className="border-t border-dashed border-black my-3" /><div className="space-y-0.5 text-[11px]"><div className="flex justify-between"><span>Subtotal</span><span>{sale.items.reduce((a,i)=>a+i.price*i.qty-(i.discount||0),0).toLocaleString('en-US',{minimumFractionDigits:2})}</span></div>{sale.discount>0&&<div className="flex justify-between"><span>Discount</span><span>- {fmtRs(sale.discount,false)}</span></div>}{(sale.tradeIn?.value || 0)>0&&<div className="flex justify-between"><span>Trade-in</span><span>- {fmtRs(sale.tradeIn?.value || 0,false)}</span></div>}{sale.tax>0&&<div className="flex justify-between"><span>Tax</span><span>{fmtRs(sale.tax,false)}</span></div>}{(sale.shipping||0)>0&&<div className="flex justify-between"><span>Delivery / other</span><span>{fmtRs(sale.shipping||0,false)}</span></div>}{(sale.pointsRedeemed||0)>0&&<div className="flex justify-between"><span>Points ({sale.pointsRedeemed} × Rs. {Math.max(0, Number(st.loyaltyPointValue ?? POINT_VALUE))})</span><span>- {fmtRs((sale.pointsRedeemed||0)*Math.max(0, Number(st.loyaltyPointValue ?? POINT_VALUE)),false)}</span></div>}<div className="flex justify-between font-bold text-[14px] pt-1"><span>TOTAL</span><span>{fmtRs(sale.total,false)}</span></div>{sale.payments&&sale.payments.length>1?salePayments(sale).map((l,i)=><div key={i} className="flex justify-between"><span>Paid · {PAYMENT_LABEL[l.method]}</span><span>{fmtRs(l.amount,false)}</span></div>):<div className="flex justify-between"><span>Paid ({PAYMENT_LABEL[sale.payment]})</span><span>{fmtRs(sale.amountPaid,false)}</span></div>}{sale.change>0&&<div className="flex justify-between"><span>Change</span><span>{fmtRs(sale.change,false)}</span></div>}{sale.payment==='credit'&&sale.total-sale.amountPaid>0&&<div className="flex justify-between font-bold"><span>BALANCE DUE</span><span>{fmtRs(sale.total-sale.amountPaid,false)}</span></div>}{(sale.pointsEarned||0)>0&&<div className="flex justify-between text-[10px]"><span>Loyalty points earned</span><span>+{sale.pointsEarned} pts</span></div>}</div>
    <div className="border-t border-dashed border-black my-3" /><div className="text-center text-[10px] space-y-1"><div>{st.receiptFooter}</div><div className="opacity-70">Powered by NEXFIX POS v3.1</div></div>
  </div></div>;
}

export function buildWhatsAppText(sale: Sale, shop: { shopName: string; phone: string }): string { const L:string[]=[]; L.push(`*${shop.shopName}*`); L.push(`Bill: ${sale.billNo}`); L.push(`Date: ${fmtDateTime(sale.date)}`); L.push(`Cashier: ${sale.cashierName}`); L.push('--------------------------------'); sale.items.forEach(it=>{const net=it.price*it.qty-(it.discount||0);L.push(`${it.name} x${it.qty} — Rs. ${net.toLocaleString('en-US',{minimumFractionDigits:2})}`);}); L.push('--------------------------------'); if(sale.discount>0)L.push(`Discount: -Rs. ${sale.discount.toLocaleString()}`); if(sale.tax)L.push(`Tax: Rs. ${sale.tax.toLocaleString()}`); if(sale.shipping)L.push(`Delivery: Rs. ${sale.shipping.toLocaleString()}`); L.push(`*TOTAL: Rs. ${sale.total.toLocaleString('en-US',{minimumFractionDigits:2})}*`); if(sale.note)L.push(`Note: ${sale.note}`); L.push(''); L.push('Thank you for shopping with us!'); L.push(shop.phone); return L.join('\n'); }
function printA4Invoice(){const restore=()=>document.body.classList.remove('printing-invoice');document.body.classList.add('printing-invoice');window.addEventListener('afterprint',restore,{once:true});window.print();window.setTimeout(restore,1500);}
export default function ReceiptModal({ sale,onClose,onNewSale }:{sale:Sale|null;onClose:()=>void;onNewSale?:()=>void;}){const{state}=usePOS();if(!sale)return null;const customer=sale.customerId?state.customers.find(c=>c.id===sale.customerId):undefined;const waUrl=customer?.phone?waLink(customer.phone,buildWhatsAppText(sale,state.settings)):'';return <><Modal open={!!sale} onClose={onClose} title="Sale completed" sub={`Bill ${sale.billNo} saved to sales history`}><div className="bg-raised rounded-2xl p-4 max-h-[46vh] overflow-y-auto border border-line"><ReceiptSheet sale={sale}/></div><div className="flex flex-col sm:flex-row gap-2.5 mt-5"><button className="btn btn-primary flex-1" onClick={()=>window.print()}><Printer size={15}/> Print receipt</button><button className="btn btn-soft flex-1" onClick={printA4Invoice}><FileText size={15}/> Print A4 invoice</button>{waUrl&&<a href={waUrl} target="_blank" rel="noreferrer" className="btn flex-1 !text-white" style={{background:'linear-gradient(135deg,#25d366,#128c7e)',boxShadow:'0 8px 20px -6px rgba(18,140,126,.5)'}}><MessageCircle size={15}/> WhatsApp receipt</a>}<button className="btn btn-soft flex-1" onClick={()=>{onClose();onNewSale?.();}}><Plus size={15}/> New sale</button></div></Modal><ReceiptSheet sale={sale} forPrint/><InvoiceSheet sale={sale}/></>; }
