/**
 * Nexfix POS - Google Sheets Backup / Sync Web App
 *
 * IMPORTANT:
 * 1. Deploy this script as a Web app.
 * 2. Execute as: Me
 * 3. Who has access: Anyone
 * 4. Use the /macros/s/.../exec URL in Nexfix POS.
 *
 * This version accepts the browser form transport used by driveSync.ts:
 *   e.parameter.payload -> JSON string
 * It also accepts raw JSON in e.postData.contents for direct requests.
 */

function getSpreadsheet_() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  if (!ss) {
    throw new Error('No active spreadsheet. Bind this Apps Script project to the Nexfix POS Google Sheet.');
  }
  return ss;
}

function json_(data, callback) {
  var text = JSON.stringify(data);
  if (callback) {
    // callback is generated by the Nexfix POS browser and is not user data.
    return ContentService
      .createTextOutput(callback + '(' + text + ');')
      .setMimeType(ContentService.MimeType.JAVASCRIPT);
  }
  return ContentService
    .createTextOutput(text)
    .setMimeType(ContentService.MimeType.JSON);
}

function parseRequest_(e) {
  var raw = '';

  // Browser-safe form POST from Nexfix POS.
  if (e && e.parameter && e.parameter.payload) {
    raw = e.parameter.payload;
  }

  // Fallback for direct application/json POST requests.
  if (!raw && e && e.postData && e.postData.contents) {
    raw = e.postData.contents;
  }

  if (!raw) throw new Error('Empty request payload.');

  // If a form transport ever sends the encoded field literally, decode it.
  try {
    return JSON.parse(raw);
  } catch (firstError) {
    try {
      return JSON.parse(decodeURIComponent(raw));
    } catch (secondError) {
      throw new Error('Invalid JSON payload: ' + firstError.message);
    }
  }
}

function makeCell_(value) {
  if (value === undefined || value === null) return '';
  if (typeof value === 'object') return JSON.stringify(value);
  return value;
}

function writeRows_(sheet, rows, replaceAll) {
  if (!rows || !rows.length) return 0;

  var headers = Object.keys(rows[0]);
  var existingLastCol = sheet.getLastColumn();

  if (replaceAll || sheet.getLastRow() === 0 || existingLastCol === 0) {
    sheet.clearContents();
    sheet.clearFormats();
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
  } else {
    var existingHeaders = sheet.getRange(1, 1, 1, existingLastCol).getValues()[0];
    var merged = existingHeaders.slice();
    headers.forEach(function(h) {
      if (merged.indexOf(h) === -1) merged.push(h);
    });

    if (merged.length !== existingHeaders.length) {
      sheet.getRange(1, 1, 1, merged.length).setValues([merged]);
    }
    headers = merged;
  }

  var values = rows.map(function(row) {
    return headers.map(function(header) {
      return makeCell_(row[header]);
    });
  });

  var startRow = Math.max(sheet.getLastRow() + 1, 2);
  sheet.getRange(startRow, 1, values.length, headers.length).setValues(values);
  return values.length;
}

function formatSheet_(sheet) {
  var lastRow = sheet.getLastRow();
  var lastCol = sheet.getLastColumn();
  if (!lastRow || !lastCol) return;

  sheet.getRange(1, 1, 1, lastCol)
    .setBackground('#1e293b')
    .setFontColor('#ffffff')
    .setFontWeight('bold')
    .setVerticalAlignment('middle');

  sheet.setRowHeight(1, 30);

  for (var i = 1; i <= lastCol; i++) {
    sheet.autoResizeColumn(i);
    sheet.setColumnWidth(i, Math.max(sheet.getColumnWidth(i) + 15, 110));
  }
}

function saveData_(data) {
  if (!data.table) throw new Error('Missing table name.');
  if (!Array.isArray(data.rows)) throw new Error('rows must be an array.');

  var ss = getSpreadsheet_();
  var table = String(data.table);
  var sheet = ss.getSheetByName(table);
  if (!sheet) sheet = ss.insertSheet(table);

  // Products is a snapshot: replace the whole inventory.
  // Sales / repairs / returns / other tables are append-only.
  var replaceAll = table.toLowerCase() === 'products';
  var count = writeRows_(sheet, data.rows, replaceAll);
  formatSheet_(sheet);
  SpreadsheetApp.flush();

  return { rows: count, table: table, mode: replaceAll ? 'replace' : 'append' };
}

function backupState_(data) {
  var ss = getSpreadsheet_();
  var sheet = ss.getSheetByName('FullBackup');
  if (!sheet) sheet = ss.insertSheet('FullBackup');

  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, 5).setValues([[
      'requestId', 'savedAt', 'kind', 'exportedAt', 'stateJson'
    ]]);
  }

  var stateJson = JSON.stringify(data.state === undefined ? null : data.state);
  sheet.appendRow([
    data.requestId || '',
    new Date(),
    data.kind || 'manual',
    data.exportedAt || '',
    stateJson
  ]);

  formatSheet_(sheet);
  SpreadsheetApp.flush();
  return { table: 'FullBackup', rows: 1 };
}

function doPost(e) {
  var lock = LockService.getScriptLock();
  lock.waitLock(15000);

  var requestId = '';

  try {
    var data = parseRequest_(e);
    requestId = String(data.requestId || '');

    var result;
    if (data.action === 'saveData') {
      result = saveData_(data);
    } else if (data.action === 'backupState') {
      result = backupState_(data);
    } else {
      throw new Error('Unknown action: ' + data.action);
    }

    // Frontend checks this through doGet?action=backupStatus.
    if (requestId) {
      CacheService.getScriptCache().put(
        'backup:' + requestId,
        JSON.stringify({ ok: true, status: 'success', result: result }),
        300
      );
    }

    return json_({
      ok: true,
      status: 'success',
      requestId: requestId,
      result: result
    });
  } catch (err) {
    var message = err && err.message ? err.message : String(err);

    if (requestId) {
      CacheService.getScriptCache().put(
        'backup:' + requestId,
        JSON.stringify({ ok: false, status: 'error', message: message }),
        300
      );
    }

    return json_({
      ok: false,
      status: 'error',
      requestId: requestId,
      message: message
    });
  } finally {
    lock.releaseLock();
  }
}

function doGet(e) {
  var params = (e && e.parameter) ? e.parameter : {};
  var action = params.action || 'ping';
  var callback = params.callback || '';

  try {
    if (action === 'ping') {
      return json_({
        ok: true,
        status: 'success',
        version: '2.0.0',
        message: 'Nexfix POS Sync API is running',
        spreadsheet: getSpreadsheet_().getName()
      }, callback);
    }

    if (action === 'backupStatus') {
      var requestId = params.requestId || '';
      var cached = requestId
        ? CacheService.getScriptCache().get('backup:' + requestId)
        : null;

      if (!cached) {
        return json_({ ok: false, status: 'pending', requestId: requestId }, callback);
      }

      var status = JSON.parse(cached);
      status.requestId = requestId;
      return json_(status, callback);
    }

    if (action === 'getTable') {
      var table = String(params.table || '');
      if (!table) throw new Error('Missing table name.');

      var sheet = getSpreadsheet_().getSheetByName(table);
      if (!sheet || sheet.getLastRow() < 2 || sheet.getLastColumn() < 1) {
        return json_({ ok: true, rows: [], table: table }, callback);
      }

      var values = sheet.getDataRange().getValues();
      var headers = values.shift().map(String);
      var rows = values.map(function(row) {
        var obj = {};
        headers.forEach(function(header, index) {
          obj[header] = row[index];
        });
        return obj;
      });

      return json_({ ok: true, rows: rows, table: table }, callback);
    }

    throw new Error('Unknown action: ' + action);
  } catch (err) {
    return json_({
      ok: false,
      status: 'error',
      message: err && err.message ? err.message : String(err)
    }, callback);
  }
}
